<a href="https://colab.research.google.com/github/nedokormysh/GB_PyTorch/blob/lesson1/GB_PyTorch_hw_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# 1. Создайте случайный FloatTensor размера 3x4x5

In [16]:
# 1. Создайте случайный FloatTensor размера 3x4x5
rndmtrch = torch.randn(3, 4, 5)
rndmtrch

tensor([[[ 0.2987,  1.0057,  0.3604, -1.1335,  0.7548],
         [ 1.3940, -0.9088, -2.4047, -1.6099, -0.5704],
         [ 0.2544,  1.5988, -0.8653, -0.4810, -1.5008],
         [-0.8254,  0.4958, -0.7911,  2.2163, -0.2015]],

        [[ 0.7171,  1.4209, -0.2432, -0.2605,  0.5415],
         [ 0.8985,  1.5341,  0.5363, -0.2110, -0.3284],
         [-0.0271, -2.4887,  0.4618, -0.7337,  0.3618],
         [-2.1512,  0.4196,  0.0587,  0.4010,  0.5116]],

        [[ 0.5428,  0.0757, -1.9655, -1.2713, -0.3388],
         [ 1.8097, -0.4705,  0.9660,  1.0393, -0.0566],
         [-0.9560,  0.0123,  0.5308, -0.9158,  0.7238],
         [-1.4814, -0.6956,  0.3941, -0.2602,  0.6693]]])

In [28]:
rndmtrch.type()

'torch.FloatTensor'

# 2. Выведите его форму (shape)

In [20]:
# 2. Выведите его форму (shape)
rndmtrch.shape

torch.Size([3, 4, 5])

# 3. Приведите его к форме 6х10

In [39]:
# 3. Приведите его к форме 6х10
a = rndmtrch.reshape(6, 10)
a.shape
a

tensor([[ 0.2987,  1.0057,  0.3604, -1.1335,  0.7548,  1.3940, -0.9088, -2.4047,
         -1.6099, -0.5704],
        [ 0.2544,  1.5988, -0.8653, -0.4810, -1.5008, -0.8254,  0.4958, -0.7911,
          2.2163, -0.2015],
        [ 0.7171,  1.4209, -0.2432, -0.2605,  0.5415,  0.8985,  1.5341,  0.5363,
         -0.2110, -0.3284],
        [-0.0271, -2.4887,  0.4618, -0.7337,  0.3618, -2.1512,  0.4196,  0.0587,
          0.4010,  0.5116],
        [ 0.5428,  0.0757, -1.9655, -1.2713, -0.3388,  1.8097, -0.4705,  0.9660,
          1.0393, -0.0566],
        [-0.9560,  0.0123,  0.5308, -0.9158,  0.7238, -1.4814, -0.6956,  0.3941,
         -0.2602,  0.6693]])

# 4. Создайте случайный IntTensor размера 10

In [53]:
# 4. Создайте случайный IntTensor размера 10

b = torch.randint(30, (10,)).type(torch.IntTensor)
b

tensor([29, 22, 14,  6,  6, 16,  0, 21, 10,  8], dtype=torch.int32)

In [45]:
b.type()

'torch.IntTensor'

In [46]:
b.shape

torch.Size([10])

# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [68]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

d = a * b
d

tensor([[  8.6617,  22.1249,   5.0456,  -6.8009,   4.5290,  22.3042,  -0.0000,
         -50.4995, -16.0989,  -4.5632],
        [  7.3786,  35.1740, -12.1143,  -2.8858,  -9.0047, -13.2067,   0.0000,
         -16.6127,  22.1628,  -1.6116],
        [ 20.7960,  31.2601,  -3.4049,  -1.5629,   3.2487,  14.3758,   0.0000,
          11.2627,  -2.1103,  -2.6271],
        [ -0.7854, -54.7513,   6.4655,  -4.4023,   2.1706, -34.4196,   0.0000,
           1.2321,   4.0104,   4.0926],
        [ 15.7421,   1.6646, -27.5167,  -7.6279,  -2.0330,  28.9559,  -0.0000,
          20.2852,  10.3929,  -0.4524],
        [-27.7238,   0.2700,   7.4315,  -5.4950,   4.3427, -23.7026,  -0.0000,
           8.2759,  -2.6017,   5.3544]])

# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [111]:
# d.matmul(d.T)

In [75]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

c = a.matmul(a.T)
c

tensor([[14.5540, -2.3676,  1.3552, -5.6985, -0.2983, -0.8411],
        [-2.3676, 12.3588,  1.1704, -1.8525,  2.9033, -1.4740],
        [ 1.3552,  1.1704,  6.5540, -4.7912,  2.3440, -2.5183],
        [-5.6985, -1.8525, -4.7912, 12.3067, -3.9466,  4.3304],
        [-0.2983,  2.9033,  2.3440, -3.9466, 11.4075, -2.9235],
        [-0.8411, -1.4740, -2.5183,  4.3304, -2.9235,  5.9078]])

In [76]:
c.size()

torch.Size([6, 6])

# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [77]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)

y = x ** 3 + z - 75 * t
y.backward()

x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

# 8. Создайте единичный тензор размера 5x6

In [83]:
# 8. Создайте единичный тензор размера 5x6

ones = torch.ones(5, 6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

# 9. Переведите его в формат numpy

In [85]:
# 9. Переведите его в формат numpy

ones_n = ones.numpy()
ones_n

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

# * 10. Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

В ссылке с видео этого задания не было. И в методчиках тоже подобных ходов не было. Поэтому не совсем понятно, что нужно было делать. Вероятно ошибочно что-то попытался.

In [103]:
from torch import nn 
from torch import optim
from torch.autograd import Variable

In [104]:
x = torch.FloatTensor([1])
w1 = Variable(torch.FloatTensor([1]), requires_grad=True)

y = x ** w1 - 2 * x ** 2 + 5

In [106]:
crit = nn.MSELoss()
optimizer = optim.SGD([w1], lr=0.001)
optimizer.zero_grad()

In [107]:
w1 = nn.Linear(1, 1, bias=False)

In [108]:
optimizer.zero_grad()
x = torch.FloatTensor([5])

pred = x ** w1(torch.FloatTensor([1])) -2 * x**2 + 5
loss = crit(pred, y)
print(loss)

tensor(2356.8638, grad_fn=<MseLossBackward0>)


In [109]:
loss.backward()
optimizer.step()

In [110]:
print(pred)
print(w1)
print(w1.weight.grad)

tensor([-44.5475], grad_fn=<AddBackward0>)
Linear(in_features=1, out_features=1, bias=False)
tensor([[-70.7048]])
